MaleFashion/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MaleFashion.Models;

namespace MaleFashion.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        QLTHOITRANGContext db = new QLTHOITRANGContext();
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            LienHe contact = new LienHe();
            contact.EMAIL = fc["Email"];
            contact.HoTen = fc["HoTen"];
            contact.NgayGui = DateTime.Now;
            contact.NoiDung = fc["NoiDung"];
            db.LienHes.Add(contact);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");

        }
    }
}

MaleFashion/Views/Contact/Index.cshtml
@model MaleFashion.Models.LienHe
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!-- Map Begin -->
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d111551.9926412813!2d-90.27317134641879!3d38.606612219170856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2sbd!4v1597926938024!5m2!1sen!2sbd" height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>
<!-- Map End -->
<!-- Contact Section Begin -->
<section class="contact spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="contact__text">
                    <div class="section-title">
                        <span>Information</span>
                        <h2>Contact Us</h2>
                        <p>
                            As you might expect of a company that began as a high-end interiors contractor, we pay
                            strict attention.
                        </p>
                    </div>
                    <ul>
                        <li>
                            <h4>America</h4>
                            <p>195 E Parker Square Dr, Parker, CO 801 <br />+43 982-314-0958</p>
                        </li>
                        <li>
                            <h4>France</h4>
                            <p>109 Avenue Léon, 63 Clermont-Ferrand <br />+12 345-423-9893</p>
                        </li>
                    </ul>
                </div>
            </div>


            @ViewBag.ErrorMessage
            <div class="col-lg-6 col-md-6">
                <div class="contact__form">

                    @using (Html.BeginForm("Index", "Contact", FormMethod.Post))
                    {
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="text" name="HoTen" placeholder="Name">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" name="Email" placeholder="Email">
                            </div>
                            <div class="col-lg-12">
                                <textarea name="NoiDung" placeholder="Message"></textarea>
                                <button type="submit" class="site-btn">Send Message</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Section End -->